In [1]:
import numpy as np
import pandas as pd

from math import *

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

# Attributes

## Create empty design matrix

In [2]:
designMatrix = pd.DataFrame(columns = [
    'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address',
    'Class',
] ) 

## Import data and populate designMatrix

In [3]:
lineNum = 0

for line in open("Files/data.txt", "r"):
    lineSplit = line.strip().split(",")
    designMatrix.loc[lineNum] = lineSplit   
    lineNum+=1
    
designMatrix

SFH PopUpWindow SSL_Final_State Request_URL URL_of_Anchor Web_Traffic  \
0      1          -1               1          -1            -1           1   
1     -1          -1              -1          -1            -1           0   
2      1          -1               0           0            -1           0   
3      1           0               1          -1            -1           0   
4     -1          -1               1          -1             0           0   
...   ..         ...             ...         ...           ...         ...   
1348  -1          -1              -1          -1            -1          -1   
1349  -1           0               1           0            -1           0   
1350  -1           0              -1          -1            -1           0   
1351   0           0               1           0             0           0   
1352   1           0               1           1             1           0   

     URL_Length Age_Of_Domain IP_Address Class  
0             1             1          0     0  
1             1             1          1     1  
2            -1             1          0     1  
3             1             1          0     0  
4            -1             1          0     1  
...         ...           ...        ...   ...  
1348          0             1          0     1  
1349          0             1          0    -1  
1350         -1            -1          0     1  
1351         -1             1          0     1  
1352         -1            -1          0    -1  

[1353 rows x 10 columns]

## Split into training, validation and testing data¶

In [4]:
trainData, testData = train_test_split(designMatrix, test_size = 0.4)

testData, valData = train_test_split(testData, test_size = 0.5)

In [5]:
print("trainData size: " + str(len(trainData)))
print("valData size: " + str(len(valData)))
print("testData size: " + str(len(testData)))

trainData size: 811
valData size: 271
testData size: 271


## Splitting the train,val and test data and converting them into their own lists

In [6]:
tr= trainData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
train = np.array(tr,  dtype = np.float64)
print(train)

tst =  testData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
test = np.array(tst,  dtype = np.float64)

vl =  valData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
val = np.array(vl,  dtype = np.float64)

[[ 1.  1.  1. ...  1.  0. -1.]
 [ 1.  1.  1. ...  1.  0. -1.]
 [-1.  0.  1. ...  1.  1.  1.]
 ...
 [ 1. -1.  0. ... -1.  0.  1.]
 [-1.  0.  1. ...  1.  0.  1.]
 [-1.  0. -1. ... -1.  0.  1.]]


## We now divide our data according to classes and attributes

In [7]:
def class_divide(train):
    
    class1 = ([])
    class2 = ([])
    class3 = ([])
    
    for x in range(len(train)):
        row_data = train[x]
        #print(row_data)
        class_val = row_data[-1]
    
        if class_val == 0.0:
            class1=np.append(class1,row_data)
        elif class_val == 1.0:
            class2=np.append(class2,row_data)
        elif class_val == -1.0:
            class3=np.append(class3,row_data) 

    print(len(class1))
    class1 = np.reshape(class1,(int (len(class1)/10),10))
    #print(class1)
    #print(class1.shape)

    print(len(class2))
    class2 = np.reshape(class2,(int (len(class2)/10),10))
    #print(class2)
    #print(class2.shape)

    print(len(class3))
    class3 = np.reshape(class3,(int (len(class3)/10),10))
    #print(class3)
    #print(class3.shape)
    
    return class1,class2,class3

In [8]:
#class1 = ([])
#class2 = ([])
#class3 = ([])

class1,class2,class3 = class_divide(train)
#class1,class2,class3 = class_divide(test) #For Test Data
#class1,class2,class3 = class_divide(val) #For Validation Data

print("Class 0 with shape ", class1.shape)
print(class1)
print("Class 1 with shape ", class2.shape)
print(class2)
print("Class -1 with shape ", class3.shape)
print(class3)

690
3170
4250
Class 0 with shape  (69, 10)
[[-1. -1.  1. -1. -1.  1.  1.  1.  0.  0.]
 [ 1. -1. -1. -1.  1. -1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  1.  1.  1.  0.]
 [-1. -1.  1. -1.  1.  1.  0. -1.  0.  0.]
 [-1. -1.  0. -1. -1. -1. -1.  1.  0.  0.]
 [-1. -1.  0. -1. -1. -1.  1.  1.  0.  0.]
 [-1.  1.  1. -1.  1. -1.  0.  1.  1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 1.  0.  1. -1. -1. -1.  1.  1.  0.  0.]
 [-1.  0.  0.  0. -1. -1. -1.  1.  0.  0.]
 [ 1. -1.  1. -1. -1.  1.  1.  1.  0.  0.]
 [ 1.  0. -1. -1.  1. -1.  1.  1.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  1.  0.  0.]
 [ 1.  1.  1. -1. -1. -1.  1.  1.  0.  0.]
 [ 1.  0.  1. -1. -1. -1.  1.  1.  0.  0.]
 [-1. -1.  1. -1. -1. -1.  1.  1.  0.  0.]
 [ 1.  0.  1. -1. -1.  0.  1.  1.  0.  0.]
 [-1.  0.  0. -1. -1. -1.  0.  1.  0.  0.]
 [-1. -1.  1. -1.  1.  1.  0.  1.  0.  0.]
 [-1. -1.  0. -1. -1. -1. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  1.  0.  0.]
 [-1.  0.  0.  0. -1. -1. -1.  1.  0.  0.]
 [-1.  0.  

## We get the mean of the columns for each class

In [9]:
def mean(Class):
    sum = 0
    t_class= Class.T
    #print(t_class)
    #print(t_class.shape[1])
    #print(len(t_class))

    meanArr = ([])

    for i in range (len(t_class)):
        sum = np.sum(t_class[i])
        mean = sum/t_class.shape[1]
        meanArr = np.append(meanArr,mean)

    #print(meanArr)    
    return meanArr

## We get the Standard Deviation of the columns for each class

In [10]:
def std_dev(Class):
    meanArr = mean(Class)
    varianceArr = ([])
    t_class= Class.T
    sum=0
    for i in range (t_class.shape[0]):
        for j in range (t_class.shape[1]):
            sum = sum + ((t_class[i][j]-meanArr[i])**2)
        
        varianceArr = np.append(varianceArr,(sum/t_class.shape[1]))
        sum=0
    return np.sqrt(varianceArr)   

In [11]:
print("class 1 mean")
print(mean(class1))
print("class 2 mean")
print(mean(class2))
print("class 3 mean")
print(mean(class3))
print()

print("class 1 standard deviation")
print(std_dev(class1))
print("class 2 standard deviation")
print(std_dev(class2))
print("class 3 standard deviation")
print(std_dev(class3))

print("class 1 count")
print(class1.shape[0])
print("class 2 count")
print(class2.shape[0])
print("class 3 count")
print(class3.shape[0])

class 1 mean
[-0.08695652 -0.34782609  0.46376812 -0.8115942  -0.31884058 -0.17391304
  0.33333333  0.44927536  0.10144928  0.        ]
class 2 mean
[-0.45425868 -0.65930599 -0.18611987 -0.42271293 -0.37539432  0.2555205
 -0.2681388  -0.05993691  0.09463722  1.        ]
class 3 mean
[ 0.81411765  0.07294118  0.68470588  0.          0.28470588 -0.15529412
  0.03529412  0.38823529  0.11529412 -1.        ]

class 1 standard deviation
[0.92844159 0.73870405 0.67200134 0.39103587 0.84257634 0.88393917
 0.7924767  0.89339333 0.30192271 0.        ]
class 2 standard deviation
[0.75476771 0.47394261 0.7983005  0.65344626 0.87792427 0.73725306
 0.71533055 0.99820217 0.2927132  0.        ]
class 3 standard deviation
[0.57867047 0.63752984 0.65034034 0.86228152 0.88723044 0.79963313
 0.73958747 0.92156028 0.31937656 0.        ]
class 1 count
69
class 2 count
317
class 3 count
425


## We get the Gaussian Probability Density Function

In [12]:
def calc_probability(data_point, mean, stdev):
    exponent = exp (-((data_point-mean)**2 / (2 * stdev**2 )))
    
    return (1 / (sqrt(2 * pi) * stdev)) * exponent

In [13]:
print(calc_probability(1.0, 1.0, 1.0))

0.3989422804014327


In [14]:
def class_probabilities(class1,class2,class3, row):
    total_rows = 1353
    probabilities = dict()
    
    #class 1
    probabilities[0] = class1.shape[0]/total_rows
    for i in range(9):
        mean_class1=mean(class1)
        std_class1=std_dev(class1)
        probabilities[0] *= calc_probability(row[i], mean_class1[i], std_class1[i])
        
    #class 2
    probabilities[1] = class2.shape[0]/total_rows
    for i in range(9):
        mean_class2=mean(class2)
        std_class2=std_dev(class2)
        probabilities[1] *= calc_probability(row[i], mean_class2[i], std_class2[i])
    
    #class 3
    probabilities[2] = class3.shape[0]/total_rows
    for i in range(9):
        mean_class3=mean(class3)
        std_class3=std_dev(class3)
        probabilities[2] *= calc_probability(row[i], mean_class3[i], std_class3[i])
    return probabilities

In [15]:
#testing..
print(calc_probability(0.0, 1.0, 1.0))


0.24197072451914337


In [16]:
#testing..

probabilities = class_probabilities(class1,class2,class3,class3[0])
print(probabilities)

{0: 9.370139825832568e-06, 1: 1.6649647606460364e-08, 2: 5.676296157503559e-05}


In [17]:
def class_prediction(class1,class2,class3, row):
    probabilities = class_probabilities(class1,class2,class3, row)
    
    best_label = None
    best_prob = -1
    
    for class_value, probability in probabilities.items():
        if best_label is None or probability > best_prob:
            best_prob = probability
            best_label = class_value
    if best_label==2:
        best_label=-1
    return best_label

In [18]:
def naive_bayes_calculation(class1,class2,class3, data):
    predictions = list()
    
    for row in data:
        
        out= class_prediction(class1,class2,class3, row)
        predictions.append(out)
        
    return predictions

In [19]:
#print(test)
#print(test.shape)
print()
print('Our model predictions...')
print()

#print(naive_bayes_calculation(class1,class2,class3, train))
print(naive_bayes_calculation(class1,class2,class3, test)) #Done For Test Data
#print(naive_bayes_calculation(class1,class2,class3, val)) #Done For Validation Data



Our model predictions...

[-1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, -1, 1, 0, -1, -1, -1, 1, -1, -1, -1, 1, 1, 1, 1, -1, -1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, 0, 1, -1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, -1, -1, 0, 1, -1, -1, -1, 1, -1, -1, 1, 0, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 0, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, 1, 1, 1, 1, -1, -1, 0, 1, 1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 0, -1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 0, -1, 1, -1, 1, -1, 1]


In [20]:


def accuracy(class1,class2,class3,data):
    
    #Variables used in confusion matrix
    true_count0 = 0
    true_count1 = 0
    true_count_neg1 = 0
    pred1_when0 = 0
    pred1_when_neg1 = 0
    pred0_when1 = 0
    pred0_when_neg1= 0
    pred_neg1_when0 = 0
    pred_neg1_when1 = 0
    
    counter=0
    
    predictions=naive_bayes_calculation(class1,class2,class3, data)
    
    for x in range(data.shape[0]):
        
        if predictions[x] == 0 and data[x][-1] == 0:
            true_count0 = true_count0+1
        if predictions[x] == 1 and data[x][-1]== 1: 
            true_count1 = true_count1+1
        if predictions[x] == -1 and data[x][-1] == -1: 
            true_count_neg1 = true_count_neg1+1   
        
        if predictions[x] == 1 and data[x][-1] == 0: 
            pred1_when0 = pred1_when0+1
        if predictions[x] == 1 and data[x][-1] == -1: 
            pred1_when_neg1 = pred1_when_neg1+1 
        
        if predictions[x] == 0 and data[x][-1] == 1: 
            pred0_when1 = pred0_when1+1
        if predictions[x] == 0 and data[x][-1] == -1: 
            pred0_when_neg1= pred0_when_neg1+1
        
        if predictions[x] == -1 and data[x][-1] == 0: 
            pred_neg1_when0 = pred_neg1_when0+1
        if predictions[x] == -1 and data[x][-1] == 1: 
             pred_neg1_when1 = pred_neg1_when1+1 
    
        if predictions[x] == data[x][-1]:
            counter=counter+1
    return true_count0,true_count1,true_count_neg1,pred1_when0,pred1_when_neg1,pred0_when1,pred0_when_neg1, pred_neg1_when0,pred_neg1_when1,((counter/data.shape[0])*100)

In [26]:
print('Model Accuracy..')

#true_count0,true_count1,true_count_neg1,pred1_when0,pred1_when_neg1,pred0_when1,pred0_when_neg1, pred_neg1_when0,pred_neg1_when1,acc = accuracy(class1,class2,class3,train)
#true_count0,true_count1,true_count_neg1,pred1_when0,pred1_when_neg1,pred0_when1,pred0_when_neg1, pred_neg1_when0,pred_neg1_when1,acc = accuracy(class1,class2,class3,test)
true_count0,true_count1,true_count_neg1,pred1_when0,pred1_when_neg1,pred0_when1,pred0_when_neg1, pred_neg1_when0,pred_neg1_when1,acc = accuracy(class1,class2,class3,val)

print(acc)
print('Error..')
print(100-acc)
print()

print("True predictions for 0,1,-1")            
print(true_count0)
print(true_count1)
print(true_count_neg1)
print()
print("Total Correct Predictions")
print(true_count0+true_count1+true_count_neg1)
print()

print("False prediction 1 when value was 0 and -1")   
print(pred1_when0)
print(pred1_when_neg1)
print()

print("False prediction 0 when value was 1 and -1") 
print(pred0_when1)
print(pred0_when_neg1)
print()

print("False prediction -1 when value was 0 and 1") 
print(pred_neg1_when0)
print(pred_neg1_when1)
print()

Model Accuracy..
84.87084870848709
Error..
15.129151291512912

True predictions for 0,1,-1
4
91
135

Total Correct Predictions
230

False prediction 1 when value was 0 and -1
3
9

False prediction 0 when value was 1 and -1
6
2

False prediction -1 when value was 0 and 1
9
12



In [27]:
print("\t \t Predicted")
print("\t \t", "0 ","\t"," 1","\t"," -1")
print("actual 0 \t",true_count0,"\t", pred1_when0,"\t",pred_neg1_when0)
print("actual 1 \t",pred0_when1,"\t", true_count1,"\t",pred_neg1_when1)
print("actual -1 \t",pred0_when_neg1,"\t", pred1_when_neg1,"\t",true_count_neg1)

	 	 Predicted
	 	 0  	  1 	  -1
actual 0 	 4 	 3 	 9
actual 1 	 6 	 91 	 12
actual -1 	 2 	 9 	 135
