In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

# Attributes

## Create empty design matrix

In [4]:
designMatrix = pd.DataFrame(columns = [
    'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address',
    'Class',
] ) 

## Import data and populate designMatrix

In [5]:
lineNum = 0

for line in open("Files/data.txt", "r"):
    lineSplit = line.strip().split(",")
    designMatrix.loc[lineNum] = lineSplit   
    lineNum+=1
    
designMatrix

SFH PopUpWindow SSL_Final_State Request_URL URL_of_Anchor Web_Traffic  \
0      1          -1               1          -1            -1           1   
1     -1          -1              -1          -1            -1           0   
2      1          -1               0           0            -1           0   
3      1           0               1          -1            -1           0   
4     -1          -1               1          -1             0           0   
...   ..         ...             ...         ...           ...         ...   
1348  -1          -1              -1          -1            -1          -1   
1349  -1           0               1           0            -1           0   
1350  -1           0              -1          -1            -1           0   
1351   0           0               1           0             0           0   
1352   1           0               1           1             1           0   

     URL_Length Age_Of_Domain IP_Address Class  
0             1             1          0     0  
1             1             1          1     1  
2            -1             1          0     1  
3             1             1          0     0  
4            -1             1          0     1  
...         ...           ...        ...   ...  
1348          0             1          0     1  
1349          0             1          0    -1  
1350         -1            -1          0     1  
1351         -1             1          0     1  
1352         -1            -1          0    -1  

[1353 rows x 10 columns]

## Split into training, validation and testing data¶

In [6]:
trainData, testData = train_test_split(designMatrix, test_size = 0.4)

testData, valData = train_test_split(testData, test_size = 0.5)

In [7]:
print("trainData size: " + str(len(trainData)))
print("valData size: " + str(len(valData)))
print("testData size: " + str(len(testData)))

trainData size: 811
valData size: 271
testData size: 271


## Splitting the train,val and test data and converting them into their own lists

In [8]:
tr= trainData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
train = np.array(tr,  dtype = np.float64)
print(train)

tst =  testData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
test = np.array(tst,  dtype = np.float64)

vl =  valData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
val = np.array(vl,  dtype = np.float64)

[[ 1. -1.  1. ...  1.  0.  1.]
 [-1. -1.  1. ... -1.  0.  0.]
 [ 0. -1. -1. ... -1.  1.  1.]
 ...
 [ 1.  0.  1. ...  1.  0. -1.]
 [ 1.  1.  1. ...  1.  1. -1.]
 [ 1. -1.  0. ...  1.  0.  1.]]


## We now divide our data according to classes and attributes

In [47]:
def class_divide():
    
    class1 = ([])
    class2 = ([])
    class3 = ([])
    
    for x in range(len(train)):
        row_data = train[x]
        #print(row_data)
        class_val = row_data[-1]
    
        if class_val == 0.0:
            class1=np.append(class1,row_data)
        elif class_val == 1.0:
            class2=np.append(class2,row_data)
        elif class_val == -1.0:
            class3=np.append(class3,row_data) 

    print(len(class1))
    class1 = np.reshape(class1,(int (len(class1)/10),10))
    #print(class1)
    #print(class1.shape)

    print(len(class2))
    class2 = np.reshape(class2,(int (len(class2)/10),10))
    #print(class2)
    #print(class2.shape)

    print(len(class3))
    class3 = np.reshape(class3,(int (len(class3)/10),10))
    #print(class3)
    #print(class3.shape)
    
    return class1,class2,class3

In [49]:
#class1 = ([])
#class2 = ([])
#class3 = ([])

class1,class2,class3 = class_divide()

print("Class 0 with shape ", class1.shape)
print(class1)
print("Class 1 with shape ", class2.shape)
print(class2)
print("Class -1 with shape ", class3.shape)
print(class3)

670
3370
4070
Class 0 with shape  (67, 10)
[[-1. -1.  1. -1.  1.  1.  1. -1.  0.  0.]
 [-1. -1.  1. -1.  1.  0. -1. -1.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 1.  0.  1. -1. -1. -1.  1.  1.  1.  0.]
 [ 1.  0.  1. -1. -1.  0.  1.  1.  0.  0.]
 [ 1.  1.  1. -1. -1. -1.  1.  1.  1.  0.]
 [ 1.  0.  1. -1. -1.  1.  1. -1.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  1.  0.  0.]
 [-1. -1.  0. -1. -1. -1.  0.  1.  0.  0.]
 [ 1. -1.  1. -1.  0.  1. -1. -1.  0.  0.]
 [-1. -1.  0. -1. -1. -1. -1.  1.  0.  0.]
 [-1.  0.  1. -1.  1.  0. -1.  1.  0.  0.]
 [ 1.  0.  1. -1. -1.  0.  1.  1.  0.  0.]
 [-1. -1.  1. -1. -1.  1.  1.  1.  0.  0.]
 [ 1. -1.  1. -1.  0.  1. -1.  1.  0.  0.]
 [ 1.  0.  1. -1. -1. -1.  1.  1.  0.  0.]
 [ 1. -1.  1. -1. -1.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  1.  0.  0.]
 [-1.  0.  0. -1. -1. -1. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  1.  1.  1.  0.]
 [-1. -1.  1. -1. -1. -1.  1.  1.  0.  0.]
 [-1.  1.  1. -1.  1. -1.  0.  1.  1.  0.]
 [ 0. -1.  

## We get the mean of the columns for each class

In [66]:
def mean(Class):
    sum = 0
    t_class= Class.T
    #print(t_class)
    #print(t_class.shape[1])
    #print(len(t_class))

    meanArr = ([])

    for i in range (len(t_class)):
        sum = np.sum(t_class[i])
        mean = sum/t_class.shape[1]
        meanArr = np.append(meanArr,mean)

    #print(meanArr)    
    return meanArr

## We get the Standard Deviation of the columns for each class

In [67]:
def std_dev(Class):
    meanArr = mean(Class)
    varianceArr = ([])
    t_class= Class.T
    sum=0
    for i in range (t_class.shape[0]):
        for j in range (t_class.shape[1]):
            sum = sum + ((t_class[i][j]-meanArr[i])**2)
        
        varianceArr = np.append(varianceArr,(sum/t_class.shape[1]))
        sum=0
    return np.sqrt(varianceArr)   

In [71]:
print("class 1 mean")
print(mean(class1))
print("class 2 mean")
print(mean(class2))
print("class 3 mean")
print(mean(class3))
print()

print("class 1 standard deviation")
print(std_dev(class1))
print("class 2 standard deviation")
print(std_dev(class2))
print("class 3 standard deviation")
print(std_dev(class3))

class 1 mean
[-0.07462687 -0.37313433  0.59701493 -0.8358209  -0.43283582 -0.23880597
  0.29850746  0.46268657  0.13432836  0.        ]
class 2 mean
[-0.43026706 -0.66172107 -0.20178042 -0.40356083 -0.27596439  0.24925816
 -0.24332344 -0.08011869  0.09792285  1.        ]
class 3 mean
[ 0.78869779  0.02702703  0.73218673  0.06879607  0.21867322 -0.18673219
  0.05405405  0.48894349  0.13267813 -1.        ]

class 1 standard deviation
[0.93542923 0.70891595 0.5745784  0.37043802 0.79595771 0.86541427
 0.82886229 0.88652193 0.34100477 0.        ]
class 2 standard deviation
[0.75600715 0.47312398 0.78615417 0.65620916 0.92015886 0.76080216
 0.71865246 0.99678533 0.2972103  0.        ]
class 3 standard deviation
[0.61077147 0.63226651 0.59854113 0.84712799 0.89159064 0.78029849
 0.75306223 0.87231546 0.33922654 0.        ]
