In [1]:
import numpy as np
import pandas as pd

from math import *

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

# Attributes

## Create empty design matrix

In [2]:
designMatrix = pd.DataFrame(columns = [
    'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address',
    'Class',
] ) 

## Import data and populate designMatrix

In [3]:
lineNum = 0

for line in open("Files/data.txt", "r"):
    lineSplit = line.strip().split(",")
    designMatrix.loc[lineNum] = lineSplit   
    lineNum+=1
    
designMatrix

SFH PopUpWindow SSL_Final_State Request_URL URL_of_Anchor Web_Traffic  \
0      1          -1               1          -1            -1           1   
1     -1          -1              -1          -1            -1           0   
2      1          -1               0           0            -1           0   
3      1           0               1          -1            -1           0   
4     -1          -1               1          -1             0           0   
...   ..         ...             ...         ...           ...         ...   
1348  -1          -1              -1          -1            -1          -1   
1349  -1           0               1           0            -1           0   
1350  -1           0              -1          -1            -1           0   
1351   0           0               1           0             0           0   
1352   1           0               1           1             1           0   

     URL_Length Age_Of_Domain IP_Address Class  
0             1             1          0     0  
1             1             1          1     1  
2            -1             1          0     1  
3             1             1          0     0  
4            -1             1          0     1  
...         ...           ...        ...   ...  
1348          0             1          0     1  
1349          0             1          0    -1  
1350         -1            -1          0     1  
1351         -1             1          0     1  
1352         -1            -1          0    -1  

[1353 rows x 10 columns]

## Split into training, validation and testing data¶

In [4]:
trainData, testData = train_test_split(designMatrix, test_size = 0.4)

testData, valData = train_test_split(testData, test_size = 0.5)

In [5]:
print("trainData size: " + str(len(trainData)))
print("valData size: " + str(len(valData)))
print("testData size: " + str(len(testData)))

trainData size: 811
valData size: 271
testData size: 271


## Splitting the train,val and test data and converting them into their own lists

In [6]:
tr= trainData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
train = np.array(tr,  dtype = np.float64)
print(train)

tst =  testData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
test = np.array(tst,  dtype = np.float64)

vl =  valData[[ 'SFH',
    'PopUpWindow',
    'SSL_Final_State',
    'Request_URL',
    'URL_of_Anchor',
    'Web_Traffic',
    'URL_Length',
    'Age_Of_Domain',
    'IP_Address','Class',]]
val = np.array(vl,  dtype = np.float64)

[[ 1.  0. -1. ... -1.  0. -1.]
 [ 1.  1.  1. ...  1.  1. -1.]
 [ 1.  0.  1. ...  1.  0. -1.]
 ...
 [-1. -1.  1. ... -1.  0.  1.]
 [ 1. -1.  0. ... -1.  0.  1.]
 [ 1.  0.  1. ... -1.  0. -1.]]


## We now divide our data according to classes and attributes

In [7]:
def class_divide(train):
    
    class1 = ([])
    class2 = ([])
    class3 = ([])
    
    for x in range(len(train)):
        row_data = train[x]
        #print(row_data)
        class_val = row_data[-1]
    
        if class_val == 0.0:
            class1=np.append(class1,row_data)
        elif class_val == 1.0:
            class2=np.append(class2,row_data)
        elif class_val == -1.0:
            class3=np.append(class3,row_data) 

    print(len(class1))
    class1 = np.reshape(class1,(int (len(class1)/10),10))
    #print(class1)
    #print(class1.shape)

    print(len(class2))
    class2 = np.reshape(class2,(int (len(class2)/10),10))
    #print(class2)
    #print(class2.shape)

    print(len(class3))
    class3 = np.reshape(class3,(int (len(class3)/10),10))
    #print(class3)
    #print(class3.shape)
    
    return class1,class2,class3

In [8]:
#class1 = ([])
#class2 = ([])
#class3 = ([])

class1,class2,class3 = class_divide(train)

print("Class 0 with shape ", class1.shape)
print(class1)
print("Class 1 with shape ", class2.shape)
print(class2)
print("Class -1 with shape ", class3.shape)
print(class3)

700
3290
4120
Class 0 with shape  (70, 10)
[[ 0.  0.  0.  0.  0. -1.  0.  1.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  1.  0.  0.]
 [ 1.  1.  1. -1. -1. -1.  1.  1.  1.  0.]
 [-1.  0.  0. -1. -1. -1. -1.  1.  0.  0.]
 [ 1. -1.  1. -1. -1.  1.  1. -1.  0.  0.]
 [ 1. -1.  1. -1. -1. -1.  1.  1.  0.  0.]
 [-1.  0.  0. -1. -1. -1.  0.  1.  0.  0.]
 [ 1.  0. -1. -1.  1. -1.  1.  1.  0.  0.]
 [-1.  0.  0.  0. -1. -1. -1.  1.  0.  0.]
 [-1. -1.  1. -1.  1.  1.  0. -1.  0.  0.]
 [ 1. -1.  1. -1.  0.  1. -1.  1.  0.  0.]
 [-1.  0.  0.  0. -1. -1. -1.  1.  0.  0.]
 [-1. -1.  1. -1.  1.  1.  0. -1.  0.  0.]
 [ 1.  1. -1. -1.  1.  1.  1. -1.  0.  0.]
 [-1.  1.  1. -1.  1.  1.  1. -1.  1.  0.]
 [ 1.  0.  1. -1. -1. -1.  1.  1.  0.  0.]
 [-1. -1.  0. -1. -1. -1.  1.  1.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  1.  0.  0.]
 [-1. -1.  1. -1. -1.  0.  1.  1.  0.  0.]
 [ 1.  0.  1. -1. -1.  0.  1.  1.  0.  0.]
 [ 1.  0.  1. -1. -1. -1.  1.  1.  0.  0.]
 [ 1.  1.  1. -1. -1. -1.  1.  1.  1.  0.]
 [-1. -1.  

## We get the mean of the columns for each class

In [9]:
def mean(Class):
    sum = 0
    t_class= Class.T
    #print(t_class)
    #print(t_class.shape[1])
    #print(len(t_class))

    meanArr = ([])

    for i in range (len(t_class)):
        sum = np.sum(t_class[i])
        mean = sum/t_class.shape[1]
        meanArr = np.append(meanArr,mean)

    #print(meanArr)    
    return meanArr

## We get the Standard Deviation of the columns for each class

In [10]:
def std_dev(Class):
    meanArr = mean(Class)
    varianceArr = ([])
    t_class= Class.T
    sum=0
    for i in range (t_class.shape[0]):
        for j in range (t_class.shape[1]):
            sum = sum + ((t_class[i][j]-meanArr[i])**2)
        
        varianceArr = np.append(varianceArr,(sum/t_class.shape[1]))
        sum=0
    return np.sqrt(varianceArr)   

In [11]:
print("class 1 mean")
print(mean(class1))
print("class 2 mean")
print(mean(class2))
print("class 3 mean")
print(mean(class3))
print()

print("class 1 standard deviation")
print(std_dev(class1))
print("class 2 standard deviation")
print(std_dev(class2))
print("class 3 standard deviation")
print(std_dev(class3))

print("class 1 count")
print(class1.shape[0])
print("class 2 count")
print(class2.shape[0])
print("class 3 count")
print(class3.shape[0])

class 1 mean
[ 0.         -0.31428571  0.52857143 -0.82857143 -0.41428571 -0.2
  0.4         0.51428571  0.12857143  0.        ]
class 2 mean
[-0.47720365 -0.65349544 -0.19452888 -0.46808511 -0.35866261  0.23100304
 -0.27051672 -0.07598784  0.07902736  1.        ]
class 3 mean
[ 0.83495146  0.03883495  0.67718447  0.00728155  0.24757282 -0.18203883
  0.08737864  0.38834951  0.14320388 -1.        ]

class 1 standard deviation
[0.94112395 0.72787081 0.67021166 0.37688303 0.81928291 0.85523597
 0.8        0.85761892 0.33472499 0.        ]
class 2 standard deviation
[0.74800449 0.47585623 0.79426162 0.63799385 0.88499448 0.7568206
 0.70801751 0.99710874 0.26978145 0.        ]
class 3 standard deviation
[0.54589532 0.62972224 0.6462467  0.86037099 0.89598291 0.80554373
 0.74854936 0.92151216 0.35028065 0.        ]
class 1 count
70
class 2 count
329
class 3 count
412


## We get the Gaussian Probability Density Function

In [12]:
def calculate_probability(x, mean, stdev):
    exponent = exp(-((x-mean)**2 / (2 * stdev**2 )))
    return (1 / (sqrt(2 * pi) * stdev)) * exponent

In [13]:
print(calculate_probability(1.0, 1.0, 1.0))

0.3989422804014327


In [48]:
def calculate_class_probabilities(class1,class2,class3, row):
    total_rows = 1353
    probabilities = dict()
    
    #class 1
    probabilities[0] = class1.shape[0]/total_rows
    for i in range(9):
        mean_class1=mean(class1)
        std_class1=std_dev(class1)
        probabilities[0] *= calculate_probability(row[i], mean_class1[i], std_class1[i])
        
    #class 2
    probabilities[1] = class2.shape[0]/total_rows
    for i in range(9):
        mean_class2=mean(class2)
        std_class2=std_dev(class2)
        probabilities[1] *= calculate_probability(row[i], mean_class2[i], std_class2[i])
    
    #class 3
    probabilities[2] = class3.shape[0]/total_rows
    for i in range(9):
        mean_class3=mean(class3)
        std_class3=std_dev(class3)
        probabilities[2] *= calculate_probability(row[i], mean_class3[i], std_class3[i])
    return probabilities

In [49]:
#testing..
print(calculate_probability(0.0, 1.0, 1.0))


0.24197072451914337


In [50]:
#testing..

probabilities = calculate_class_probabilities(class1,class2,class3,class3[0])
print(probabilities)

{0: 8.142101238767234e-08, 1: 1.821922025879058e-05, 2: 2.9170346927987934e-06}


In [61]:
def predict(class1,class2,class3, row):
    probabilities = calculate_class_probabilities(class1,class2,class3, row)
    best_label, best_prob = None, -1
    for class_value, probability in probabilities.items():
        if best_label is None or probability > best_prob:
            best_prob = probability
            best_label = class_value
    if best_label==2:
        best_label=-1
    return best_label

In [74]:
def naive_bayes(class1,class2,class3, test):
    predictions = list()
    for row in test:
        output = predict(class1,class2,class3, row)
        predictions.append(output)
    return predictions

In [75]:
print(test)
print()
print('Our model predictions...')
print()
print(naive_bayes(class1,class2,class3, test))


[[ 1.  0. -1. ...  1.  0. -1.]
 [ 1.  1.  1. ...  1.  0. -1.]
 [ 1.  0.  1. ... -1.  0. -1.]
 ...
 [ 1.  0.  1. ... -1.  0. -1.]
 [-1.  0.  1. ...  1.  1. -1.]
 [ 1.  0.  1. ...  1.  0. -1.]]

Our model predictions...

[-1, -1, -1, 1, -1, 0, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 0, 1, 1, 1, 1, -1, -1, -1, 0, 1, 1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 0, 0, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, 0, -1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, -1, 0, 1, -1, 1, -1, 1, 0, -1, -1, 1, 1, -1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, 0, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 0, 1, 1, -1, -1, -1, 1, -1, -1, 1, -1

In [84]:
def accuracy(class1,class2,class3,test):
    counter=0;
    predictions=naive_bayes(class1,class2,class3, test)
    for x in range(test.shape[0]):
        if predictions[x]==test[x][-1]:
            counter=counter+1
    return (counter/test.shape[0])*100

In [85]:
print('Model Accuracy..')
print(accuracy(class1,class2,class3,test))

Model Accuracy..
80.44280442804428
